### ISSUE TITLE
Fix export form entries to filter by widget_id

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#169]

**Comment by luizalbsilva** [comment]
endpoint?

**Comment by lpirola** [comment]
@luizalbsilva yep, form_entries, consegue achar aí?

**Comment by luizalbsilva** [comment]
There is a filter in that endpoint and it works

**Comment by luizalbsilva** [comment]
You can test it even from wget:

In this one, you will get all form_entries related to 159 mobilization
wget --header="Accept: application/json" --header="Access-Token: <YOUR TOKEN HERE>" --header="Client: <YOUR CLIENT ID HERE>" --header="Token-Type: Bearer" --header="Uid: <YOUR UID HERE>"  http://localhost:3000/mobilizations/159/form_entries

This one you will get none, since that id has no form_entry
wget --header="Accept: application/json" --hewget --header="Accept: application/json" --header="Access-Token: <YOUR TOKEN HERE>" --header="Client: <YOUR CLIENT ID HERE>" --header="Token-Type: Bearer" --header="Uid: <YOUR UID HERE>"  http://localhost:3000/mobilizations/159/form_entries?widget_id=21

Those data are from our staging server

**Comment by gabrielrtakeda** [comment]
Nice @luizalbsilva! I did not know that passing the `widget_id` as a query param was working. I will fix the way that frontend consumes this endpoint.

Thanks for the help! (:
