### ISSUE TITLE
Add filter by tags and period to mobilizations

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#175]

**Comment by luizalbsilva** [comment]
I'm bugged about the requests of too many tags... take a looK:

"The HTTP protocol does not place any a priori limit on the length of a URI. Servers MUST be able to handle the URI of any resource they serve, and SHOULD be able to handle URIs of unbounded length if they provide GET-based forms that could generate such URIs. A server SHOULD return 414 (Request-URI Too Long) status if a URI is longer than the server can handle (see section 10.4.15).

Note: Servers should be cautious about depending on URI lengths above 255 bytes, because some older client or proxy implementations may not properly support these lengths."
http://stackoverflow.com/questions/266322/is-there-a-limit-to-the-length-of-a-get-request

**Comment by lpirola** [comment]
@luizalbsilva I bet that theses is not a problem because we will search one tag by time. Could you elaborate in which scenarios that could be a threat?
