### ISSUE TITLE
Add Search tags by text

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#177]

**Comment by lpirola** [comment]
@devton we are wondering if that it's not the case to use elasticsearch. What do you think?

**Comment by devton** [comment]
@lpirola we don't need to use elastic search for this kind of search, just a tsvector to use full text search of postgres

**Comment by luizalbsilva** [comment]
Well, guys, I was thinking about this:

We really need another technology? Can't we do the search on the mobilization's name? Because we'll get a lot of trouble to update information each time someone updates those data. I was thinking about this, and I'd like your opinions...

Oh, yes, to  simplify search on activists, maybe we could do this:
- have 2 tags attributes, one for user's tags, another for 'automatic tags'. I'm not quite sure if we need this, we could have just one with no problem... was just an idea if we need to visually separate those tags
- automatic tags will only be given to activists. a letter (or 2) to identify the type of record, and a number with id. For example, if one signs a pessure, he could receive the following tags: M112(for mob 112), B225(block 225), W1221(Widget 1221), P123122(pressure 123122)
- if the user select some kind of data, we will already have the id's and kind of mobilization, so, we will just filter the activists with the tags

What do you guys think? @lpirola @devton ?

**Comment by lpirola** [comment]
@luizalbsilva I like, seems great to filter with an easier tool. How attributes works in tag gems?
